import os



Import('env')

# import and create a copy of the environment so we don't screw up anyone elses env.
myenv=env.Clone()

cpppath=''' 
	 $IRDB_SDK/include 
	 $SECURITY_TRANSFORMS_HOME/include
	 $SMPSA_HOME/include
	'''


files=Glob( Dir('.').srcnode().abspath+"/*.cpp")


pgm="zax.exe"

LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split("stars "+ env.subst('$BASE_IRDB_LIBS')+ "  irdb-cfg irdb-util irdb-transform irdb-elfdep irdb-deep ") 
myenv=myenv.Clone(CPPPATH=Split(cpppath))
myenv.Append(CXXFLAGS = " -std=c++11 -Wall -g -fmax-errors=2 ")
pgm=myenv.Program(pgm,  files,  LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/plugins_install/", pgm)
Default(install)

	
	
Return('install')
