# @HEADER_LANG python
# @HEADER_COMPONENT zafl
# @HEADER_BEGIN
#
# Copyright (c) 2018-2019 Zephyr Software LLC
#
# This file may be used and modified for non-commercial purposes as long as
# all copyright, permission, and nonwarranty notices are preserved.
# Redistribution is prohibited without prior written consent from Zephyr
# Software.
#
# Please contact the authors for restrictions applying to commercial use.
#
# THIS SOURCE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
# Author: Zephyr Software
# e-mail: jwd@zephyr-software.com
# URL   : http://www.zephyr-software.com/
#
# This software was developed with SBIR funding and is subject to SBIR Data Rights, 
# as detailed below.
#
# SBIR DATA RIGHTS
#
# Contract No. __FA8750-17-C-0295___________________________.
# Contractor Name __Zephyr Software LLC_____________________.
# Address __4826 Stony Point Rd, Barboursville, VA 22923____.
#


# @HEADER_END
import os

Import('env')

# import and create a copy of the environment so we don't screw up anyone elses env.
myenv=env.Clone()

cpppath=''' 
	 $IRDB_SDK/include 
	'''

files=Glob( Dir('.').srcnode().abspath+"/*.cpp")

pgm="zax.exe"

LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split(" irdb-core irdb-cfg irdb-util irdb-transform irdb-elfdep irdb-deep ") 
myenv=myenv.Clone(CPPPATH=Split(cpppath))
myenv.Append(CXXFLAGS = " -std=c++11 -Wall -fmax-errors=2 ")
pgm=myenv.Program(pgm,  files,  LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$ZAFL_HOME/zafl_plugins/", pgm)
Default(install)

	
	
Return('install')
