import shutil
import os
import tarfile

Import('env')

(sysname, nodename, release, version, machine)=os.uname()

env.Append(CXXFLAGS=" -Wall -Werror")
env.Append(LINKFLAGS=" -Wall -Werror -Wl,-unresolved-symbols=ignore-in-shared-libs ")

env['BASE_IRDB_LIBS']="irdb-core"


# pebliss requires iconv, which needs to be explicit on cygwin.
if "CYGWIN" in sysname:
	# add tuple of 1 item!
	env['BASE_IRDB_LIBS']=env['BASE_IRDB_LIBS']+("iconv",)

Export('env')

libs=SConscript("tools/SConscript", variant_dir='scons_build/tools')

pedi = Command( target = "./testoutput",
		source = "./SConscript",
                action = "cd "+os.environ['SECURITY_TRANSFORMS_HOME']+" ; " +os.environ['PEDI_HOME']+"/pedi -m manifest.txt ; cd -" )

Depends(pedi,libs)


Default( pedi )

