#   
#   Copyright 2017-2019 University of Virginia
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#


# 
# import and create a copy of the environment so we don't screw up anyone elses env.
#
Import('env')
cpppath='$IRDB_SDK/include'
libpath="$IRDB_LIBS"
myenv=env.Clone( CPPPATH=cpppath, LIBPATH=libpath)

#
# set the files to build and the output file name
#
files=Glob( Dir('.').srcnode().abspath+"/*.cpp")
pgm="libzedge.so"

#
# override the default libs as we need more libraries for this transform
# 
libs=Split("irdb-core  irdb-transform irdb-deep irdb-util ") 

#
# build and install the transform, by default
# 
pgm=myenv.SharedLibrary(pgm,  files,  LIBS=libs)
install=myenv.Install("$ZAFL_HOME/zafl_plugins/", pgm)
Default(install)


#
# and we're done
#
Return('install')
